name: CI

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      # Maven cache
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Build code
      - name: Build & Test
        run: ./mvnw test
